/*
 * This file is generated by jOOQ.
 */
package com.dw.dwproject.api.model;


import com.dw.dwproject.api.model.tables.User;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
